# Generated by Django 5.1.9 on 2026-08-22 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(choices=[('kaizen', 'Kaizen Continuous Improvement'), ('fives', '5S Workplace Organization'), ('ppsr', 'PPSR Problem Solving'), ('safety_desk', 'Safety Desk & Red Flags')], max_length=50)),
                ('role_name', models.CharField(choices=[('initiator', 'Initiator / Operator'), ('committee', 'Committee Member / Reviewer'), ('coordinator', 'Module Coordinator / Lead'), ('admin', 'Module Administrator')], default='initiator', max_length=50)),
                ('mini_factory', models.CharField(choices=[('MF1', 'Mini-Factory 1 (MF1)'), ('MF2', 'Mini-Factory 2 (MF2)'), ('MF3', 'Mini-Factory 3 (MF3)'), ('Central', 'Plant Central / Shared'), ('ALL', 'All Mini-Factories (Global)')], default='MF1', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_module_roles',
                'ordering': ['user', 'module_code'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='mini_factory',
            field=models.CharField(blank=True, default='MF1', help_text='Primary assigned Mini-Factory (e.g. MF1, MF2, MF3, Central)', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forces user to change their temporary password on first login'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('initiator', 'Initiator'), ('reviewer', 'Reviewer / Manager'), ('kaizen_lead', 'Kaizen Lead / CFT Member'), ('cft_member', 'CFT Member'), ('verifier', 'Verifier'), ('admin', 'Administrator'), ('superadmin', 'Super Administrator')], max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['mini_factory'], name='users_mini_fa_d67157_idx'),
        ),
        migrations.AddField(
            model_name='usermodulerole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_module_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermodulerole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usermodulerole',
            unique_together={('user', 'module_code')},
        ),
    ]
