# Generated by Django 4.2.30 on 2026-10-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodulerole_module_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulerole',
            name='module_code',
            field=models.CharField(choices=[('kaizen', 'Kaizen Continuous Improvement'), ('fives', '5S Workplace Organization'), ('ppsr', 'PPSR Problem Solving'), ('safety_desk', 'Safety Desk & Red Flags'), ('tpm', 'TPM Total Productive Maintenance'), ('mps', 'MPS Supply Chain & Inventory'), ('checklist', 'Checklist Daily Work Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodulerole',
            name='role_name',
            field=models.CharField(choices=[('initiator', 'Initiator / Operator'), ('committee', 'Committee Member / Reviewer'), ('coordinator', 'Module Coordinator / Lead'), ('admin', 'Module Administrator'), ('demand_planner', 'Demand Planner'), ('supply_planner', 'Supply / Buyer'), ('production', 'Production & Shop Floor'), ('management', 'Plant Management'), ('operator', 'Checklist Operator / Verification')], default='initiator', max_length=50),
        ),
    ]
