"""
Live End-to-End PPSR Initiator Verification Script
===================================================
Tests live authentication, form submission, and SQLite database storage
for the PPSR Initiator role against the running Django server.
"""

import os
import sys
import json
import requests
from datetime import date

# Configure Django environment for direct ORM verification
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
import django
django.setup()

from ppsr.models import (
    PpsrReport,
    ContainmentAction,
    CorrectiveAction,
    StandardizationItem,
    ReadAcrossItem,
    FiveWhysChain,
)

BASE_URL = 'http://127.0.0.1:8000'

def run_e2e_verification():
    print("=" * 70)
    print("STARTING PPSR INITIATOR LIVE END-TO-END VERIFICATION")
    print("=" * 70)

    # 1. Authenticate as initiator 'swaraj'
    session = requests.Session()
    login_url = f"{BASE_URL}/api/v1/auth/login/"
    print(f"\n[STEP 1] Logging in as Initiator 'swaraj' via {login_url}...")
    
    login_payload = {
        'username': 'swaraj',
        'password': 'Password@123',
    }
    login_resp = session.post(login_url, json=login_payload)
    if login_resp.status_code != 200:
        print(f"FAILED to login: {login_resp.status_code} - {login_resp.text}")
        sys.exit(1)
    
    login_data = login_resp.json()
    payload_data = login_data.get('data', {})
    user_info = payload_data.get('user', {})
    access_token = payload_data.get('tokens', {}).get('access')
    if access_token:
        session.headers['Authorization'] = f'Bearer {access_token}'

    print(f" -> User Info keys: {list(user_info.keys())}")
    role_name = user_info.get('roleCategory') or user_info.get('role_category') or (user_info.get('roleDetail') or user_info.get('role_detail') or {}).get('name')
    print(f" -> Login SUCCESS! User: {user_info.get('username')}, Role: {role_name}")
    assert role_name == 'initiator', f"Expected role 'initiator', got '{role_name}'"

    # 2. Build complete 5-step form payload as generated by frontend
    today_str = date.today().isoformat()
    form_payload = {
        # Step 1: General Parameters & 5W2H
        'title': 'High Noise and Vibration in Hydraulic Power Unit - Live Test',
        'problemStatement': 'Acoustic levels exceeding 85dB at Line 2 Station 4 during high pressure pump cycle.',
        'plant': 'Pune Assembly & Paint Complex',
        'lineStation': 'Line 2 - Stn 4',
        'productComponent': 'HPU-Pump-500-V2',
        'amountDefects': '4 units per shift',
        'discoveredOn': today_str,
        'discoveredBy': 'Swaraj Matre',
        'repeatCase': 'no',
        'initialEvidenceType': 'data',
        'leadOwner': 'Swaraj Matre',
        'projectLeader': 'Swaraj Matre',
        'teamMembers': 'Rahul Sharma, Sunita Rao (Assigned Quality Team)',
        'targetDate': today_str,
        'status': 'Open',
        'factsAnalysis': {
            'whatIs': 'Pump housing vibration exceeding 4.5 mm/s',
            'whatIsNot': 'Drive motor shaft wobble',
            'whereIs': 'Station 4 HPU assembly bench',
            'whereIsNot': 'Station 1 component staging area',
            'howIs': 'Excess pressure relief valve chatter',
            'howIsNot': 'Electrical inverter frequency noise',
            'whenIs': 'Occurs after 15 minutes of continuous operation',
            'whenIsNot': 'Does not occur during cold startup'
        },
        'initialDefectTrendData': [
            {'date': 'Day 1', 'defectsCount': 6.2, 'stage': 'Initial Baseline'},
            {'date': 'Day 2', 'defectsCount': 4.1, 'stage': 'Observation'}
        ],

        # Step 2: Emergency Containment Actions
        'containmentActionsList': [
            {
                'action': 'Install secondary rubber dampener bracket on pump base',
                'responsible': 'Amit Deshmukh',
                'date': today_str,
                'status': 'implemented'
            },
            {
                'action': '100% acoustic inspection of all finished pumps before shipment',
                'responsible': '',  # Test auto-fallback to lead_owner
                'date': today_str,
                'status': 'implemented'
            }
        ],

        # Step 3: Cause Localization & Root Cause Analysis
        'causeLocalizationApproach': 'both',
        'ishikawa': {
            'man': ['Operator variation during torque tightening'],
            'machine': ['Relief valve spring tension calibration drift'],
            'material': ['O-ring hardness batch variation'],
            'methods': ['Standard operating procedure revision pending'],
            'milieu': ['Ambient temperature in test enclosure > 38C'],
            'measurement': ['Decibel meter calibration interval overdue']
        },
        'psqTreeData': {
            'root': 'High Noise Root Cause',
            'branches': ['Mechanical', 'Hydraulic', 'Electrical']
        },
        'standardWorksheet': [
            {'step': 1, 'cause': 'Spring tension fatigue', 'root_cause': 'Relief valve spring tension drift'}
        ],
        'fiveWhysList': {
            'column1': [
                'Why was noise high? High hydraulic resonance.',
                'Why high resonance? Relief valve chattering rapidly.',
                'Why chattering? Spring tension fell below 45 N.',
                'Why spring tension low? Fatigue under high duty cycle.',
                'Why fatigued? Material spec did not specify shot-peened wire.'
            ],
            'column2': ['Hydraulic fluid temperature reached 55C.'],
            'column3': []
        },

        # Step 4: Permanent Corrective Actions & Verification
        'correctiveActionsList': [
            {
                'measure': 'Change spring specification to shot-peened high-tensile alloy (PN: SP-990)',
                'responsible': 'Pooja Kulkarni',
                'deadline': today_str,
                'status': 'completed'
            }
        ],
        'effectivenessEvidence': 'Noise level dropped from 86.4 dB to 71.2 dB across 50 production cycles.',
        'evidenceType': 'data',
        'defectTrendData': [
            {'date': 'Day 1', 'defectsCount': 6.2, 'stage': 'Initial Baseline'},
            {'date': 'Day 3', 'defectsCount': 1.1, 'stage': 'New Spring Installed'},
            {'date': 'Day 5', 'defectsCount': 0.0, 'stage': 'Current Standardized'}
        ],
        'effectivenessChartData': [
            {'name': 'Day 1', 'value': 6.2},
            {'name': 'Day 3', 'value': 1.1},
            {'name': 'Day 5', 'value': 0.0}
        ],

        # Step 5: Standardization & Read Across
        'standardizationList': [
            {
                'measure': 'Update drawing BOM and incoming quality inspection standard (IQS-HPU-04)',
                'responsible': 'Swaraj Matre',
                'date': today_str,
                'status': 'completed'
            }
        ],
        'readAcrossList': [
            {
                'proposal': 'Inspect and retrofit identical relief valves on Line 1 & Line 3 HPUs',
                'responsible': 'Ramesh Shinde',
                'deadline': today_str
            }
        ],
        'readAcrossExplanation': 'Deploy to all plant HPU test cells to prevent recurrence.',
        'completionSignatures': {
            'projectLeader': 'Swaraj Matre',
            'steeringCommittee': 'Committee Chairperson',
            'completedOn': today_str
        }
    }

    # 3. Submit PPSR via POST /api/v1/ppsr/reports/
    post_url = f"{BASE_URL}/api/v1/ppsr/reports/"
    print(f"\n[STEP 2] Submitting 5-step PPSR Form via {post_url}...")
    post_resp = session.post(post_url, json=form_payload)
    if post_resp.status_code != 201:
        print(f"FAILED to create PPSR: {post_resp.status_code} - {post_resp.text}")
        sys.exit(1)

    created_data = post_resp.json()
    report_id = created_data.get('id')
    ppsr_no = created_data.get('ppsr_no') or created_data.get('ppsrNo')
    print(f" -> Form Submitted SUCCESSFULLY! HTTP 201 Created")
    print(f" -> Generated PPSR ID: {report_id}")
    print(f" -> Generated PPSR No: {ppsr_no}")

    # 4. Direct SQLite Database Inspection
    print(f"\n[STEP 3] Inspecting SQLite Database directly via Django ORM...")
    report = PpsrReport.objects.filter(id=report_id).first()
    assert report is not None, f"PPSR Report with ID {report_id} not found in database!"

    print(f" [DB VERIFIED] PpsrReport record found:")
    print(f"   - ppsr_no: {report.ppsr_no}")
    print(f"   - title: {report.title}")
    print(f"   - problem_statement: {report.problem_statement}")
    print(f"   - plant: {report.plant}")
    print(f"   - line_station: {report.line_station}")
    print(f"   - product_component: {report.product_component}")
    print(f"   - amount_defects: {report.amount_defects}")
    print(f"   - discovered_on: {report.discovered_on}")
    print(f"   - discovered_by: {report.discovered_by}")
    print(f"   - repeat_case: {report.repeat_case}")
    print(f"   - lead_owner: {report.lead_owner}")
    print(f"   - project_leader: {report.project_leader}")
    print(f"   - team_members: {report.team_members}")
    print(f"   - target_date: {report.target_date}")
    print(f"   - status: {report.status}")

    # Check 5W2H Facts Analysis
    print(f"\n [DB VERIFIED] 5W2H Facts Analysis (JSONField):")
    print(f"   - whatIs: {report.facts_analysis.get('whatIs')}")
    print(f"   - what_is: {report.facts_analysis.get('what_is')}")
    print(f"   - whereIs: {report.facts_analysis.get('whereIs')}")
    print(f"   - howIs: {report.facts_analysis.get('howIs')}")
    print(f"   - whenIs: {report.facts_analysis.get('whenIs')}")
    assert report.facts_analysis.get('whatIs') == 'Pump housing vibration exceeding 4.5 mm/s'
    assert report.facts_analysis.get('whereIs') == 'Station 4 HPU assembly bench'

    # Check Initial Defect Trend Data
    print(f"\n [DB VERIFIED] Initial Trend Data (JSONField):")
    print(f"   - rows count: {len(report.initial_defect_trend_data)}")
    print(f"   - row 1: {report.initial_defect_trend_data[0]}")
    assert len(report.initial_defect_trend_data) == 2

    # Check Containment Actions Table
    print(f"\n [DB VERIFIED] Containment Actions Table (Child Rows):")
    containments = list(ContainmentAction.objects.filter(report=report).order_by('no'))
    print(f"   - Total rows saved: {len(containments)}")
    for c in containments:
        print(f"     * #{c.no}: action='{c.action[:45]}...', responsible='{c.responsible}', status='{c.status}'")
    assert len(containments) == 2
    assert containments[1].responsible == 'Swaraj Matre', "Responsible should auto-fallback to lead_owner"

    # Check Ishikawa & 5-Whys
    print(f"\n [DB VERIFIED] Cause Localization & Root Cause:")
    print(f"   - approach: {report.cause_localization_approach}")
    print(f"   - ishikawa machine causes: {report.ishikawa.get('machine')}")
    five_whys = FiveWhysChain.objects.filter(report=report).first()
    assert five_whys is not None, "FiveWhysChain must be saved in database"
    print(f"   - Five-Whys Column 1 count: {len(five_whys.column1)}")
    for idx, why in enumerate(five_whys.column1, 1):
        print(f"     Why #{idx}: {why}")
    assert len(five_whys.column1) == 5

    # Check Corrective Actions Table
    print(f"\n [DB VERIFIED] Corrective Actions Table (Child Rows):")
    correctives = list(CorrectiveAction.objects.filter(report=report).order_by('no'))
    print(f"   - Total rows saved: {len(correctives)}")
    for ca in correctives:
        print(f"     * #{ca.no}: measure='{ca.measure[:45]}...', responsible='{ca.responsible}', status='{ca.status}'")
    assert len(correctives) == 1

    # Check Standardization Items Table
    print(f"\n [DB VERIFIED] Standardization Items Table (Child Rows):")
    standardizations = list(StandardizationItem.objects.filter(report=report).order_by('no'))
    print(f"   - Total rows saved: {len(standardizations)}")
    for st in standardizations:
        print(f"     * #{st.no}: measure='{st.measure[:45]}...', responsible='{st.responsible}', status='{st.status}'")
    assert len(standardizations) == 1

    # Check Read-Across Items Table
    print(f"\n [DB VERIFIED] Read-Across Items Table (Child Rows):")
    read_across = list(ReadAcrossItem.objects.filter(report=report).order_by('no'))
    print(f"   - Total rows saved: {len(read_across)}")
    for ra in read_across:
        print(f"     * #{ra.no}: proposal='{ra.proposal[:45]}...', responsible='{ra.responsible}'")
    assert len(read_across) == 1
    print(f"   - read_across_explanation: {report.read_across_explanation}")

    # Check Completion Signatures
    print(f"\n [DB VERIFIED] Completion Signatures (JSONField):")
    print(f"   - projectLeader: {report.completion_signatures.get('projectLeader')}")
    print(f"   - steeringCommittee: {report.completion_signatures.get('steeringCommittee')}")
    print(f"   - completedOn: {report.completion_signatures.get('completedOn')}")
    assert report.completion_signatures.get('projectLeader') == 'Swaraj Matre'

    # 5. Fetch Register via GET /api/v1/ppsr/reports/
    print(f"\n[STEP 4] Fetching PPSR Register list via GET /api/v1/ppsr/reports/...")
    list_resp = session.get(f"{BASE_URL}/api/v1/ppsr/reports/")
    assert list_resp.status_code == 200, f"Register fetch failed: {list_resp.status_code}"
    list_data = list_resp.json()
    items = list_data.get('results', list_data) if isinstance(list_data, dict) else list_data
    found = any((it.get('ppsr_no') == report.ppsr_no or it.get('ppsrNo') == report.ppsr_no) for it in items)
    print(f" -> Found in PPSR Register list? {found}")
    assert found, "Created PPSR report must be visible in Register list"

    # 6. Fetch Full Details via GET /api/v1/ppsr/reports/{id}/
    print(f"\n[STEP 5] Fetching Full Sheet Inspection via GET /api/v1/ppsr/reports/{report.id}/...")
    detail_resp = session.get(f"{BASE_URL}/api/v1/ppsr/reports/{report.id}/")
    assert detail_resp.status_code == 200, f"Detail fetch failed: {detail_resp.status_code}"
    detail_data = detail_resp.json()
    c_actions = detail_data.get('containmentActionsList') or detail_data.get('containmentActions') or []
    ca_actions = detail_data.get('correctiveActionsList') or detail_data.get('correctiveActions') or []
    s_items = detail_data.get('standardizationList') or detail_data.get('standardizationItems') or []
    ra_items = detail_data.get('readAcrossList') or detail_data.get('readAcrossItems') or []
    fw = detail_data.get('fiveWhysList') or detail_data.get('fiveWhys') or {}
    print(f" -> Response retrieved successfully:")
    print(f"   * containment_actions count: {len(c_actions)}")
    print(f"   * corrective_actions count: {len(ca_actions)}")
    print(f"   * standardization_items count: {len(s_items)}")
    print(f"   * read_across_items count: {len(ra_items)}")
    print(f"   * five_whys column1 count: {len(fw.get('column1', []))}")
    assert len(c_actions) == 2, f"Expected 2 containment actions, got {len(c_actions)}"
    assert len(ca_actions) == 1, f"Expected 1 corrective action, got {len(ca_actions)}"
    assert len(s_items) == 1, f"Expected 1 standardization item, got {len(s_items)}"
    assert len(ra_items) == 1, f"Expected 1 read-across item, got {len(ra_items)}"
    assert len(fw.get('column1', [])) == 5, f"Expected 5 whys in column 1, got {len(fw.get('column1', []))}"

    print("\n" + "=" * 70)
    print("ALL TESTS AND DATABASE CHECKS PASSED PERFECTLY!")
    print("=" * 70)

if __name__ == '__main__':
    run_e2e_verification()
