# Generated by Django 5.1.9 on 2026-08-22 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizens', '0004_alter_kaizen_approved_by_alter_kaizen_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaizen',
            name='suggestion_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date the suggestion was made'),
        ),
    ]
