"""
End-to-End Tests for PPSR Initiator Role & Form Submission
===========================================================
Validates that an authenticated user with the 'initiator' role can fill out
the complete 5-step PPSR wizard form, submit it, and have all required and
optional fields accurately stored in the database across:
- PpsrReport (identity, 5W2H facts analysis, parameters, signatures)
- ContainmentAction child rows
- FiveWhysChain root cause drilldown
- CorrectiveAction child rows
- StandardizationItem child rows
- ReadAcrossItem horizontal deployment rows
"""

from decimal import Decimal
from datetime import date
from django.test import TestCase
from rest_framework.test import APIClient
from rest_framework import status

from accounts.models import CustomUser, Role
from ppsr.models import (
    PpsrReport,
    ContainmentAction,
    CorrectiveAction,
    StandardizationItem,
    ReadAcrossItem,
    FiveWhysChain,
)
from core.redis_client import create_session


class PpsrInitiatorE2ETestCase(TestCase):
    """End-to-end test suite for PPSR Initiator workflow."""

    def setUp(self):
        self.client = APIClient()

        # Create initiator role and user
        self.initiator_role, _ = Role.objects.get_or_create(name='initiator')
        self.initiator = CustomUser.objects.create_user(
            username='swaraj_initiator',
            email='swaraj_init@example.com',
            password='Password@123',
            role=self.initiator_role,
            first_name='Swaraj',
            last_name='Matre',
            employee_id='EMP-INIT-77',
        )

        # Authenticate via session cookie and bearer token
        self.session_key = create_session(self.initiator.id, self.initiator.username)
        self.client.cookies['kspg_sid'] = self.session_key
        self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.session_key}')
        self.client.force_authenticate(user=self.initiator)

    def test_ppsr_initiator_form_submission_and_database_persistence(self):
        """
        Simulate submitting the exact 5-step wizard form payload as sent by the frontend,
        and verify every single field and child table in the SQLite database.
        """
        today_str = date.today().isoformat()

        # Exact structure generated by Frontend/src/ppsr/PpsrSystem.tsx
        form_payload = {
            # Step 1: General Parameters
            'title': 'High Noise and Vibration in Hydraulic Power Unit',
            'problemStatement': 'Acoustic levels exceeding 85dB at Line 2 Station 4 during pump cycle.',
            'plant': 'Pune Assembly & Paint Complex',
            'lineStation': 'Line 2 - Stn 4',
            'productComponent': 'HPU-Pump-500-V2',
            'amountDefects': '4 units per shift',
            'discoveredOn': today_str,
            'discoveredBy': 'Swaraj Matre',
            'repeatCase': 'no',
            'initialEvidenceType': 'data',
            'leadOwner': 'Swaraj Matre',
            'projectLeader': 'Swaraj Matre',
            'teamMembers': 'Rahul Sharma, Sunita Rao (Assigned Quality Team)',
            'targetDate': today_str,
            'status': 'Open',

            # Step 1: 5W2H Facts Analysis
            'factsAnalysis': {
                'whatIs': 'Pump housing vibration exceeding 4.5 mm/s',
                'whatIsNot': 'Drive motor shaft wobble',
                'whereIs': 'Station 4 HPU assembly bench',
                'whereIsNot': 'Station 1 component staging area',
                'howIs': 'Excess pressure relief valve chatter',
                'howIsNot': 'Electrical inverter frequency noise',
                'whenIs': 'Occurs after 15 minutes of continuous operation',
                'whenIsNot': 'Does not occur during cold startup'
            },

            # Step 1: Initial Baseline Trend Data
            'initialDefectTrendData': [
                {'date': 'Day 1', 'defectsCount': 6.2, 'stage': 'Initial Baseline'},
                {'date': 'Day 2', 'defectsCount': 4.1, 'stage': 'Observation'}
            ],

            # Step 2: Emergency Containment Actions
            'containmentActionsList': [
                {
                    'action': 'Install secondary rubber dampener bracket on pump base',
                    'responsible': 'Amit Deshmukh',
                    'date': today_str,
                    'status': 'implemented'
                },
                {
                    'action': '100% acoustic inspection of all finished pumps before shipment',
                    'responsible': '',  # Test auto-fallback to lead_owner
                    'date': today_str,
                    'status': 'implemented'
                }
            ],

            # Step 3: Cause Localization & Root Cause Analysis
            'causeLocalizationApproach': 'both',
            'ishikawa': {
                'man': ['Operator variation during torque tightening'],
                'machine': ['Relief valve spring tension calibration drift'],
                'material': ['O-ring hardness batch variation'],
                'methods': ['Standard operating procedure revision pending'],
                'milieu': ['Ambient temperature in test enclosure > 38C'],
                'measurement': ['Decibel meter calibration interval overdue']
            },
            'psqTreeData': {
                'root': 'High Noise Root Cause',
                'branches': ['Mechanical', 'Hydraulic', 'Electrical']
            },
            'standardWorksheet': [
                {'step': 1, 'cause': 'Spring tension fatigue', 'root_cause': 'Relief valve spring tension drift'}
            ],
            'fiveWhysList': {
                'column1': [
                    'Why was noise high? High hydraulic resonance.',
                    'Why high resonance? Relief valve chattering rapidly.',
                    'Why chattering? Spring tension fell below 45 N.',
                    'Why spring tension low? Fatigue under high duty cycle.',
                    'Why fatigued? Material spec did not specify shot-peened wire.'
                ],
                'column2': ['Hydraulic fluid temperature reached 55C.'],
                'column3': []
            },

            # Step 4: Permanent Corrective Actions & Verification
            'correctiveActionsList': [
                {
                    'measure': 'Change spring specification to shot-peened high-tensile alloy (PN: SP-990)',
                    'responsible': 'Pooja Kulkarni',
                    'deadline': today_str,
                    'status': 'completed'
                }
            ],
            'effectivenessEvidence': 'Noise level dropped from 86.4 dB to 71.2 dB across 50 production cycles.',
            'evidenceType': 'data',
            'defectTrendData': [
                {'date': 'Day 1', 'defectsCount': 6.2, 'stage': 'Initial Baseline'},
                {'date': 'Day 3', 'defectsCount': 1.1, 'stage': 'New Spring Installed'},
                {'date': 'Day 5', 'defectsCount': 0.0, 'stage': 'Current Standardized'}
            ],
            'effectivenessChartData': [
                {'name': 'Day 1', 'value': 6.2},
                {'name': 'Day 3', 'value': 1.1},
                {'name': 'Day 5', 'value': 0.0}
            ],

            # Step 5: Standardization & Read Across
            'standardizationList': [
                {
                    'measure': 'Update drawing BOM and incoming quality inspection standard (IQS-HPU-04)',
                    'responsible': 'Swaraj Matre',
                    'date': today_str,
                    'status': 'completed'
                }
            ],
            'readAcrossList': [
                {
                    'proposal': 'Inspect and retrofit identical relief valves on Line 1 & Line 3 HPUs',
                    'responsible': 'Ramesh Shinde',
                    'deadline': today_str
                }
            ],
            'readAcrossExplanation': 'Deploy to all plant HPU test cells to prevent recurrence.',
            'completionSignatures': {
                'projectLeader': 'Swaraj Matre',
                'steeringCommittee': 'Committee Chairperson',
                'completedOn': today_str
            }
        }

        # 1. Submit form via POST /api/v1/ppsr/reports/
        response = self.client.post('/api/v1/ppsr/reports/', data=form_payload, format='json')
        self.assertEqual(
            response.status_code,
            status.HTTP_201_CREATED,
            f"Expected 201 Created, got {response.status_code}: {response.data}"
        )

        res_data = response.data
        report_id = res_data.get('id')
        self.assertTrue(report_id, "Response must include an ID for the created PPSR report.")

        # 2. Query the database directly via Django ORM
        report_in_db = PpsrReport.objects.filter(id=report_id).first()
        self.assertIsNotNone(report_in_db, "PPSR record must exist in the database.")

        # 3. Check all general fields saved in database
        self.assertTrue(report_in_db.ppsr_no.startswith('BE-2026-'), f"Invalid PPSR number: {report_in_db.ppsr_no}")
        self.assertEqual(report_in_db.title, 'High Noise and Vibration in Hydraulic Power Unit')
        self.assertEqual(report_in_db.problem_statement, 'Acoustic levels exceeding 85dB at Line 2 Station 4 during pump cycle.')
        self.assertEqual(report_in_db.plant, 'Pune Assembly & Paint Complex')
        self.assertEqual(report_in_db.line_station, 'Line 2 - Stn 4')
        self.assertEqual(report_in_db.product_component, 'HPU-Pump-500-V2')
        self.assertEqual(report_in_db.amount_defects, '4 units per shift')
        self.assertEqual(str(report_in_db.discovered_on), today_str)
        self.assertEqual(report_in_db.discovered_by, 'Swaraj Matre')
        self.assertEqual(report_in_db.repeat_case, 'no')
        self.assertEqual(report_in_db.lead_owner, 'Swaraj Matre')
        self.assertEqual(report_in_db.project_leader, 'Swaraj Matre')
        self.assertEqual(report_in_db.team_members, 'Rahul Sharma, Sunita Rao (Assigned Quality Team)')
        self.assertEqual(report_in_db.status, 'Open')
        self.assertEqual(str(report_in_db.target_date), today_str)

        # 4. Check JSON facts analysis
        facts = report_in_db.facts_analysis
        self.assertIsInstance(facts, dict)
        self.assertEqual(facts.get('whatIs'), 'Pump housing vibration exceeding 4.5 mm/s')
        self.assertEqual(facts.get('whereIs'), 'Station 4 HPU assembly bench')
        self.assertEqual(facts.get('howIs'), 'Excess pressure relief valve chatter')
        self.assertEqual(facts.get('whenIs'), 'Occurs after 15 minutes of continuous operation')

        # 5. Check Initial defect trend data
        self.assertEqual(len(report_in_db.initial_defect_trend_data), 2)
        self.assertEqual(report_in_db.initial_defect_trend_data[0]['stage'], 'Initial Baseline')

        # 6. Check Containment Actions in child table
        containment_count = ContainmentAction.objects.filter(report=report_in_db).count()
        self.assertEqual(containment_count, 2, "Both containment actions must be saved in database.")
        c1 = ContainmentAction.objects.filter(report=report_in_db, no=1).first()
        self.assertIn('Install secondary rubber dampener', c1.action)
        self.assertEqual(c1.responsible, 'Amit Deshmukh')
        self.assertEqual(c1.status, 'implemented')

        # Check auto-fallback of responsible to lead_owner
        c2 = ContainmentAction.objects.filter(report=report_in_db, no=2).first()
        self.assertEqual(c2.responsible, 'Swaraj Matre')

        # 7. Check Cause localization & Ishikawa
        self.assertEqual(report_in_db.cause_localization_approach, 'both')
        self.assertEqual(len(report_in_db.ishikawa.get('man', [])), 1)
        self.assertEqual(len(report_in_db.ishikawa.get('machine', [])), 1)

        # 8. Check 5-Whys Chain child table
        five_whys = FiveWhysChain.objects.filter(report=report_in_db).first()
        self.assertIsNotNone(five_whys, "FiveWhysChain record must exist in database.")
        self.assertEqual(len(five_whys.column1), 5)
        self.assertIn('Why was noise high?', five_whys.column1[0])
        self.assertEqual(len(five_whys.column2), 1)

        # 9. Check Corrective Actions in child table
        corrective_count = CorrectiveAction.objects.filter(report=report_in_db).count()
        self.assertEqual(corrective_count, 1)
        ca1 = CorrectiveAction.objects.filter(report=report_in_db, no=1).first()
        self.assertIn('Change spring specification', ca1.measure)
        self.assertEqual(ca1.responsible, 'Pooja Kulkarni')
        self.assertEqual(ca1.status, 'completed')

        # 10. Check Effectiveness evidence & trends
        self.assertIn('Noise level dropped', report_in_db.effectiveness_evidence)
        self.assertEqual(len(report_in_db.defect_trend_data), 3)
        self.assertEqual(len(report_in_db.effectiveness_chart_data), 3)

        # 11. Check Standardization items in child table
        std_count = StandardizationItem.objects.filter(report=report_in_db).count()
        self.assertEqual(std_count, 1)
        s1 = StandardizationItem.objects.filter(report=report_in_db, no=1).first()
        self.assertIn('Update drawing BOM', s1.measure)
        self.assertEqual(s1.responsible, 'Swaraj Matre')

        # 12. Check Read Across items in child table
        read_across_count = ReadAcrossItem.objects.filter(report=report_in_db).count()
        self.assertEqual(read_across_count, 1)
        ra1 = ReadAcrossItem.objects.filter(report=report_in_db, no=1).first()
        self.assertIn('retrofit identical relief valves', ra1.proposal)
        self.assertEqual(ra1.responsible, 'Ramesh Shinde')
        self.assertEqual(report_in_db.read_across_explanation, 'Deploy to all plant HPU test cells to prevent recurrence.')

        # 13. Check Signatures
        self.assertEqual(report_in_db.completion_signatures.get('projectLeader'), 'Swaraj Matre')

        # 14. Verify Register List Endpoint includes the new report
        list_resp = self.client.get('/api/v1/ppsr/reports/')
        self.assertEqual(list_resp.status_code, status.HTTP_200_OK)
        results = list_resp.data.get('results', list_resp.data)
        found_in_list = any(r.get('ppsr_no') == report_in_db.ppsr_no or r.get('ppsrNo') == report_in_db.ppsr_no for r in results)
        self.assertTrue(found_in_list, f"Newly created {report_in_db.ppsr_no} must appear in PPSR Register list.")

        # 15. Verify Detail Inspection Endpoint returns all child actions
        detail_resp = self.client.get(f'/api/v1/ppsr/reports/{report_in_db.id}/')
        self.assertEqual(detail_resp.status_code, status.HTTP_200_OK)
        self.assertEqual(len(detail_resp.data.get('containment_actions', [])), 2)
        self.assertEqual(len(detail_resp.data.get('corrective_actions', [])), 1)
        self.assertEqual(len(detail_resp.data.get('standardization_items', [])), 1)
        self.assertEqual(len(detail_resp.data.get('read_across_items', [])), 1)
