from django.urls import re_path
from .views import (
    config_view,
    health_view,
    minifactories_view,
    submit_checklist_view,
    submissions_view,
    deviations_view,
    deviation_detail_view,
    admin_audit_view,
    admin_operators_view,
    admin_export_view,
    ai_verify_gauge_view,
    master_structure_view,
    master_machines_view,
    master_machine_detail_view,
    master_checklist_detail_view,
    master_checklists_view,
    master_upload_reference_view,
    master_clear_all_view,
)

urlpatterns = [
    re_path(r'^config/?$', config_view, name='config'),
    re_path(r'^health/?$', health_view, name='health'),
    re_path(r'^minifactories/?$', minifactories_view, name='minifactories'),
    re_path(r'^checklists/submit/?$', submit_checklist_view, name='submit_checklist'),
    re_path(r'^submissions/?$', submissions_view, name='submissions'),
    re_path(r'^deviations/(?P<dev_id>[^/]+)/?$', deviation_detail_view, name='deviation_detail'),
    re_path(r'^deviations/?$', deviations_view, name='deviations'),
    re_path(r'^admin/audit/?$', admin_audit_view, name='admin_audit'),
    re_path(r'^admin/operators/?$', admin_operators_view, name='admin_operators'),
    re_path(r'^admin/export/?$', admin_export_view, name='admin_export'),
    re_path(r'^ai/verify-gauge/?$', ai_verify_gauge_view, name='ai_verify_gauge'),
    re_path(r'^master/structure/?$', master_structure_view, name='master_structure'),
    re_path(r'^master/machines/(?P<station_id>[^/]+)/?$', master_machine_detail_view, name='master_machine_detail'),
    re_path(r'^master/machines/?$', master_machines_view, name='master_machines'),
    re_path(r'^master/checklists/(?P<station_id>[^/]+)/?$', master_checklist_detail_view, name='master_checklist_detail'),
    re_path(r'^master/checklists/?$', master_checklists_view, name='master_checklists'),
    re_path(r'^master/upload-reference/?$', master_upload_reference_view, name='master_upload_reference'),
    re_path(r'^master/clear-all/?$', master_clear_all_view, name='master_clear_all'),
]
