# Generated by Django 4.2.30 on 2026-09-21 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSubmission',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('minifactory_id', models.CharField(max_length=64)),
                ('line_id', models.CharField(max_length=64)),
                ('station_id', models.CharField(max_length=128)),
                ('station_number', models.CharField(blank=True, default='', max_length=64)),
                ('line_name', models.CharField(blank=True, default='', max_length=255)),
                ('operator_name', models.CharField(blank=True, default='', max_length=255)),
                ('operator_id', models.CharField(blank=True, default='', max_length=64)),
                ('shift', models.CharField(blank=True, default='', max_length=128)),
                ('submitted_at', models.CharField(max_length=128)),
                ('completed_at', models.CharField(blank=True, default='', max_length=128)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('machine_checkpoints', models.JSONField(blank=True, default=list)),
                ('pokayoke_checkpoints', models.JSONField(blank=True, default=list)),
                ('deviations', models.JSONField(blank=True, default=list)),
                ('overall_status', models.CharField(default='OK', max_length=32)),
                ('verification_hash', models.CharField(blank=True, default='', max_length=255)),
                ('is_authentic', models.BooleanField(default=True)),
                ('photo_evidence_keys', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('station_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('machine_checkpoints', models.JSONField(blank=True, default=list)),
                ('pokayoke_checkpoints', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviationLog',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('sn', models.IntegerField(default=1)),
                ('date', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.CharField(max_length=128)),
                ('minifactory_id', models.CharField(max_length=64)),
                ('line_id', models.CharField(max_length=64)),
                ('station_id', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('problem_description', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('countermeasure', models.TextField(blank=True, default='')),
                ('target_date', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='Open', max_length=64)),
                ('checkpoint_name', models.CharField(blank=True, default='', max_length=255)),
                ('photo_evidence_url', models.TextField(blank=True, default='')),
                ('assigned_to', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.CharField(blank=True, max_length=128, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Minifactory',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StationState',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('station_id', models.CharField(max_length=128)),
                ('minifactory_id', models.CharField(max_length=64)),
                ('line_id', models.CharField(max_length=64)),
                ('status', models.CharField(default='PENDING', max_length=64)),
                ('last_submitted_at', models.CharField(blank=True, max_length=128, null=True)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('current_operator_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_verification_hash', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('minifactory_id', models.CharField(max_length=64)),
                ('line_name', models.CharField(blank=True, default='', max_length=255)),
                ('operator_name', models.CharField(blank=True, default='', max_length=255)),
                ('operator_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='PENDING', max_length=64)),
                ('shift', models.CharField(default='Shift 1 (06:00 - 14:00)', max_length=128)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('machine_checkpoints', models.JSONField(blank=True, default=list)),
                ('pokayoke_checkpoints', models.JSONField(blank=True, default=list)),
                ('deviations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='api.line')),
            ],
            options={
                'ordering': ['number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='line',
            name='minifactory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.minifactory'),
        ),
    ]
