# Generated by Django 5.1.9 on 2026-08-26 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaizens', '0005_alter_kaizen_suggestion_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human-readable label, e.g. "August 2026 Awards – MF1".', max_length=200)),
                ('mini_factory', models.CharField(choices=[('MF1', 'Mini Factory 1'), ('MF2', 'Mini Factory 2'), ('MF3', 'Mini Factory 3'), ('Central', 'Central')], default='MF1', max_length=20)),
                ('month', models.PositiveSmallIntegerField(help_text='Calendar month (1–12).')),
                ('year', models.PositiveSmallIntegerField(help_text='Calendar year, e.g. 2026.')),
                ('session_date', models.DateField(blank=True, help_text='Date on which the award session / meeting took place.', null=True)),
                ('is_finalized', models.BooleanField(default=False, help_text='Once finalized, attendance and awards are locked from editing.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_cycles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Award Cycle',
                'verbose_name_plural': 'Award Cycles',
                'ordering': ['-year', '-month', 'mini_factory'],
                'unique_together': {('mini_factory', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CftMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the CFT member.', max_length=150)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID (optional, must be unique if provided).', max_length=30, null=True, unique=True)),
                ('role', models.CharField(help_text='Job role / designation.', max_length=150)),
                ('department', models.CharField(choices=[('Quality', 'Quality'), ('Operations', 'Operations'), ('Engineering', 'Engineering'), ('Maintenance', 'Maintenance'), ('Machining', 'Machining'), ('Production', 'Production'), ('HR', 'HR'), ('Safety', 'Safety'), ('Finance', 'Finance'), ('Other', 'Other')], default='Operations', max_length=50)),
                ('mini_factory', models.CharField(choices=[('MF1', 'Mini Factory 1'), ('MF2', 'Mini Factory 2'), ('MF3', 'Mini Factory 3'), ('Central', 'Central')], default='MF1', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive members are hidden from attendance sheets and nomination lists.')),
                ('joined_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cft_members_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='System user account linked to this CFT member (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cft_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CFT Member',
                'verbose_name_plural': 'CFT Members',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('best_kaizen', 'Best Kaizen'), ('most_improved', 'Most Improved'), ('team_player', 'Team Player'), ('innovation', 'Innovation Award'), ('safety_champion', 'Safety Champion'), ('custom', 'Custom Award')], default='best_kaizen', max_length=30)),
                ('custom_award_label', models.CharField(blank=True, default='', help_text='Only used when award_type is "custom".', max_length=200)),
                ('status', models.CharField(choices=[('nominated', 'Nominated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('presented', 'Presented')], default='nominated', max_length=20)),
                ('citation', models.TextField(blank=True, default='', help_text='Reason / citation for the award.')),
                ('points', models.PositiveSmallIntegerField(default=0, help_text='Gamification points awarded (if applicable).')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_approved', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='cft_awards.awardcycle')),
                ('linked_kaizen', models.ForeignKey(blank=True, help_text='Optional: the specific Kaizen that earned this award.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='kaizens.kaizen')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='cft_awards.cftmember')),
                ('nominated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Award',
                'verbose_name_plural': 'Monthly Awards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marks', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='cft_awards.awardcycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='cft_awards.cftmember')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['cycle', 'member__name'],
                'unique_together': {('cycle', 'member')},
            },
        ),
    ]
