# Generated by Django 5.1.9 on 2026-08-26 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cft_awards', '0001_initial'),
        ('kaizens', '0005_alter_kaizen_suggestion_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CFTEvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Month name or representation, e.g. "August" or "8"', max_length=20)),
                ('year', models.PositiveIntegerField(help_text='Calendar year, e.g. 2026')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the session was created/opened')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the session was last updated')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FINALIZED', 'Finalized'), ('LOCKED', 'Locked')], default='OPEN', help_text='Session state: OPEN, FINALIZED, or LOCKED', max_length=20)),
                ('category_overrides', models.JSONField(blank=True, default=dict, help_text='Map of Kaizen ID -> CategoryKey overrides for this session')),
                ('present_member_ids', models.JSONField(blank=True, default=list, help_text='List of present CFT member IDs (strings or ints) in this session')),
                ('opened_by', models.ForeignKey(blank=True, help_text='User who opened or initialized the evaluation session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cft_sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CFT Evaluation Session',
                'verbose_name_plural': 'CFT Evaluation Sessions',
                'db_table': 'cft_evaluation_sessions',
                'ordering': ['-year', '-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CFTRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(default=0, help_text='Star rating from 1 to 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cft_ratings', to='kaizens.kaizen')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cft_ratings', to='cft_awards.cftmember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cft_awards.cftevaluationsession')),
            ],
            options={
                'verbose_name': 'CFT Kaizen Rating',
                'verbose_name_plural': 'CFT Kaizen Ratings',
                'db_table': 'cft_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cftevaluationsession',
            constraint=models.UniqueConstraint(fields=('month', 'year'), name='unique_cft_session_month_year'),
        ),
        migrations.AlterUniqueTogether(
            name='cftrating',
            unique_together={('session', 'member', 'kaizen')},
        ),
    ]
