# Generated by Django 5.1.9 on 2026-08-26 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cft_awards', '0002_cftevaluationsession_cftrating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CFTSessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True, help_text='True if member is present for the evaluation session')),
                ('marked_at', models.DateTimeField(auto_now=True, help_text='Timestamp when attendance was marked/updated')),
                ('marked_by', models.ForeignKey(blank=True, help_text='User who recorded this attendance mark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cft_session_marks', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='CFT Committee member', on_delete=django.db.models.deletion.CASCADE, related_name='session_memberships', to='cft_awards.cftmember')),
                ('session', models.ForeignKey(help_text='Evaluation session for a specific month/year', on_delete=django.db.models.deletion.CASCADE, related_name='session_members', to='cft_awards.cftevaluationsession')),
            ],
            options={
                'verbose_name': 'CFT Session Member',
                'verbose_name_plural': 'CFT Session Members',
                'db_table': 'cft_session_members',
                'ordering': ['member__department', 'member__name'],
                'constraints': [models.UniqueConstraint(fields=('session', 'member'), name='unique_session_member')],
            },
        ),
    ]
