# Generated by Django 5.1.9 on 2026-08-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cft_awards', '0003_cftsessionmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Category code identifier, e.g., 'MF1', 'MF2', 'MF3', 'Machining', 'Quality', 'Maintenance'", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Human-readable title, e.g., 'Minifactory 1 (MF1)'", max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Descriptive scope or line names', max_length=255)),
                ('winner_count', models.PositiveIntegerField(default=1, help_text='Number of allowable winners in this category')),
                ('badge_bg', models.CharField(blank=True, default='', help_text='CSS background / badge styling gradient class', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Active categories appear in monthly evaluation boards')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Award Category',
                'verbose_name_plural': 'Award Categories',
                'db_table': 'cft_award_categories',
                'ordering': ['order', 'code'],
            },
        ),
    ]
