# Generated by Django 5.1.9 on 2026-08-26 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cft_awards', '0004_awardcategory'),
        ('kaizens', '0005_alter_kaizen_suggestion_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyaward',
            options={'ordering': ['session', 'category', 'rank'], 'verbose_name': 'Monthly Award', 'verbose_name_plural': 'Monthly Awards'},
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='award_type',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='custom_award_label',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='linked_kaizen',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='member',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='nominated_by',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='points',
        ),
        migrations.RemoveField(
            model_name='monthlyaward',
            name='status',
        ),
        migrations.AddField(
            model_name='monthlyaward',
            name='category',
            field=models.CharField(default='MF1', help_text='The category code (e.g., MF1, Quality) this award was won under.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyaward',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When the award was officially finalized.', null=True),
        ),
        migrations.AddField(
            model_name='monthlyaward',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_monthly_awards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyaward',
            name='kaizen',
            field=models.ForeignKey(default=1, help_text='The winning Kaizen.', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_awards', to='kaizens.kaizen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyaward',
            name='rank',
            field=models.PositiveIntegerField(default=1, help_text='The position (1st, 2nd, etc.) won in this category.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyaward',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='The cumulative CFT score that earned this win.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyaward',
            name='session',
            field=models.ForeignKey(default=1, help_text='The CFT evaluation session this award belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_awards', to='cft_awards.cftevaluationsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyaward',
            name='winner_status',
            field=models.CharField(choices=[('PREVIEW', 'Preview'), ('FINALIZED', 'Finalized')], default='PREVIEW', help_text='PREVIEW until the session is permanently locked.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='monthlyaward',
            constraint=models.UniqueConstraint(fields=('session', 'category', 'rank'), name='unique_session_category_rank'),
        ),
        migrations.AddConstraint(
            model_name='monthlyaward',
            constraint=models.UniqueConstraint(fields=('session', 'kaizen'), name='unique_session_kaizen_award'),
        ),
        migrations.AlterModelTable(
            name='monthlyaward',
            table='cft_monthly_awards',
        ),
    ]
