# Generated by Django 5.1.9 on 2026-08-22 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('kaizens', '0005_alter_kaizen_suggestion_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='User affected by administrative actions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('rework', 'Rework'), ('classify', 'Classify'), ('impact_review', 'Impact Review'), ('action_assign', 'Action Assignment'), ('action_update', 'Action Update'), ('action_complete', 'Action Completion'), ('verify', 'Verify'), ('vote', 'Vote'), ('close', 'Close'), ('evidence_upload', 'Evidence Upload'), ('evidence_delete', 'Evidence Delete'), ('resource_allocate', 'Resource Allocate'), ('login', 'Login'), ('logout', 'Logout'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_disable', 'User Disabled'), ('user_enable', 'User Enabled'), ('role_change', 'Role Changed'), ('mini_factory_change', 'Mini-Factory Changed'), ('temp_password_reset', 'Temporary Password Reset'), ('password_force_change', 'Forced Password Change Completed')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_user'], name='audit_logs_target__3f70c6_idx'),
        ),
    ]
